### PR TITLE
@6.agl.icefish

### PR DESCRIPTION
**Pull request by jobol**

### CODE REVIEW

**Comment by jobol** [comment]
test in progress are showing an issue with url when token comes from environment
fix being studied

**Comment by jobol** [comment]
test still in progress stil doesn't work with environment variables

**Comment by jobol** [comment]
Works well now

**Comment by jaragunde** [comment]
Works for me, except for a problem that seems to be outside of WAM: https://jira.automotivelinux.org/browse/SPEC-2550?focusedCommentId=23287#comment-23287

It could be already merged, IMO.

**Pull request merged**
